apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactvitypasswdgnrtr-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: reactvitypasswdgnrtr
  template:
    metadata:
      labels:
        app: reactvitypasswdgnrtr
    spec:
      containers:
        - name: reactvitypasswdgnrtr
          image: yash5090/reactvitypasswdgnrtr:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
