apiVersion: v1
kind: Service
metadata:
  name: reactvitypasswdgnrtr-service
spec:
  selector:
    app: reactvitypasswdgnrtr
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
